[versions]
androidIdenticons = "v11"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
core = "1.7.0"
core-ktx = "1.17.0"
dagger = "2.59.1"
espresso-core = "3.7.0"
junit = "4.13.2"
junit-version = "1.3.0"
kotlin-reflect = "2.3.0"
kotlin-stdlib-jdk7 = "2.2.10"
kotlin-stdlib = "2.3.10"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines-core-version = "1.10.2"
kotlinxMetadataJvm = "0.9.0"
lifecycle = "2.10.0"
material = "1.13.0"
navigationFragmentKtxVersion = "2.9.7"
navigationUiKtxVersion = "2.9.7"
preferenceKtx = "1.2.1"
protobuf-kotlin = "4.33.5"
protobufGradlePlugin = "0.9.6"
recyclerview = "1.4.0"
room = "2.8.4"
runtime = "1.10.2"
slidingpanelayout = "1.2.0"
swiperefreshlayout = "1.2.0"

[libraries]

android-identicons = { module = "com.github.lelloman:android-identicons", version.ref = "androidIdenticons" }
androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "core" }
androidx-lifecycle-viewmodel-ktx-v287 = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment-ktx-v288 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationFragmentKtxVersion" }
androidx-navigation-ui-ktx-v288 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler-v261 = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx-v261 = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime-v261 = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-slidingpanelayout = { module = "androidx.slidingpanelayout:slidingpanelayout", version.ref = "slidingpanelayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
hilt-android-v251 = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core-version" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin-stdlib-jdk7" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvm" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
protobuf-gradle-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobufGradlePlugin" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protobuf-kotlin" }


